import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import { Toaster } from "react-hot-toast";
import "./globals.css";

const space_grotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight:["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Rick & Morty",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={space_grotesk.className}>
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "#6EE7B7",
              color: "black",
            },
          }}
        />
      </body>
    </html>
  );
}
